config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get '/movies',          to: "movies#index",    as: :movies
  post '/movies',         to: "movies#create"
  get '/movies/new',      to: "movies#new",      as: :new_movies
  get '/movies/:id/edit', to: "movies#edit",     as: :edit_movie
  get '/movies/:id',      to: "movies#show",     as: :movie
  patch '/movies/:id',    to: "movies#update"

  get '/books',           to: "books#index",     as: :books
  post '/books',          to: "books#create"
  get '/books/new',       to: "books#new",       as: :new_books
  get '/books/:id/edit',  to: "books#edit",      as: :edit_book
  get '/books/:id',       to: "books#show",      as: :book
  patch '/books/:id',     to: "books#update"

  get '/albums',          to: "albums#index",    as: :albums
  post '/albums',         to: "albums#create"
  get '/albums/new',      to: "albums#new",      as: :new_albums
  get '/albums/:id/edit', to: "albums#edit",     as: :edit_album
  get '/albums/:id',      to: "albums#show",     as: :album
  patch '/albums/:id',    to: "albums#update"

  root 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
  end

  def create
    @album = Album.new(album_params)

    @album.save
    redirect_to @album
  end

  def edit
    @album = Album.find(params[:id])
  end

  def new
  end

  def show
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render 'edit'
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :artist, :description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)

    @book.save
    redirect_to @book
  end

  def edit
    @book = Book.find(params[:id])
  end

  def new
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :description)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(movie_params)

    @movie.save
    redirect_to @movie
  end

  def edit
    @movies = Movie.find(params[:id])
  end

  def new
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'edit'
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :director, :description)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= form_for :album, url: album_path(@album), method: :patch do |f| %>
  <% if @album.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@album.errors.count, "error") %> prohibited
      this album from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :artist %><br>
    <%= f.text_area :artist %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>All Albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th>Description</th>
  </tr>

  <% @albums.each do |album| %>
    <tr>
      <td><%= album.name %></td>
      <td><%= album.artist %></td>
      <td><%= album.description %></td>
      <td><%= link_to 'Show', album_path(album) %></td>
      <td><%= link_to 'Edit', edit_album_path(album) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New album', new_albums_path %>

app/views/albums/new.html.erb
<h1>Albums#New</h1>

<%= form_for :album, url: albums_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to All Albums', albums_path %>

app/views/albums/show.html.erb
<h1>Albums#Show</h1>

<p>
  <strong>Name:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<%= link_to 'Back to All Albums', albums_path %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= form_for :book, url: book_path(@book), method: :patch do |f| %>
  <% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited
      this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :autho %><br>
    <%= f.text_area :author %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>All Books</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Author</th>
    <th>Description</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.description %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New book', new_books_path %>

app/views/books/new.html.erb
<h1>Books#New</h1>

<%= form_for :book, url: books_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to All Books', books_path %>

app/views/books/show.html.erb
<h1>Books#Show</h1>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Back to All Books', books_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

<%= link_to 'Albums', controller: 'albums' %>
<br>
<%= link_to 'Books', controller: 'books' %>
<br>
<%= link_to 'Movies', controller: 'movies' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediaRanker</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= form_for :movie, url: movie_path(@movie), method: :patch do |f| %>
  <% if @movie.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@movie.errors.count, "error") %> prohibited
      this movie from being saved:</h2>
    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :director %><br>
    <%= f.text_area :director %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>All Movies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Director</th>
    <th>Description</th>
  </tr>

  <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.name %></td>
      <td><%= movie.director %></td>
      <td><%= movie.description %></td>
      <td><%= link_to 'Show', movie_path(movie) %></td>
      <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New movie', new_movies_path %>

app/views/movies/new.html.erb
<h1>Movies#New</h1>

<%= form_for :movie, url: movies_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to All Movies', movies_path %>

app/views/movies/show.html.erb
<h1>Movies#Show</h1>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Back to All Movies', movies_path %>